language: python
python:
    - 2.7
env:
    matrix:
        - TOXENV=py27
        - TOXENV=py35
        - TOXENV=py36
        - TOXENV=py37
        - TOXENV=py38
        - TOXENV=flake8
        - TOXENV=isort
install:
    - pip install tox
script:
    - tox
