name: Release
on:
  push:
    tags:
    - '*.*.*'
  workflow_dispatch:
jobs:
  build-sdist:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: python setup.py sdist --verbose
    - uses: actions/upload-artifact@v3
      with:
        path: dist/sqlalchemy-repr-*.tar.gz
  deploy:
    needs:
    - build-sdist
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install twine
    - uses: actions/download-artifact@v3
    - run: twine upload --verbose artifact/*
      env:
        TWINE_NON_INTERACTIVE: 1
        TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
